# Generated by Django 6.0 on 2025-12-20 20:39

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('FREE', 'FREE'), ('PRO', 'PRO'), ('ENTERPRISE', 'ENTERPRISE')], max_length=50)),
                ('plan_type', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('ORGANIZATION', 'ORGANIZATION')], default='INDIVIDUAL', max_length=50)),
                ('max_documents', models.IntegerField(default=10)),
                ('max_storage_mb', models.IntegerField(default=100)),
                ('max_queries', models.IntegerField(default=100)),
                ('max_members', models.IntegerField(blank=True, help_text='NULL = ilimitado (para planos ORGANIZATION)', null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'plans',
                'indexes': [models.Index(fields=['tier'], name='plans_tier_61c541_idx'), models.Index(fields=['plan_type'], name='plans_plan_ty_0d3909_idx')],
            },
        ),
    ]
