# Generated by Django 6.0 on 2025-12-29 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0002_seed_default_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELED', 'CANCELED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=50)),
                ('current_period_start', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='plans.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['user_id', 'status'], name='subscriptio_user_id_8d58fd_idx'), models.Index(fields=['organization_id', 'status'], name='subscriptio_organiz_4f7e3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='mês/ano, ex: 2025-12-01')),
                ('documents_uploaded', models.IntegerField(default=0)),
                ('queries_executed', models.IntegerField(default=0)),
                ('storage_used_mb', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL se for uso individual', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, help_text='NULL se for uso da org', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso',
                'verbose_name_plural': 'Usos',
                'db_table': 'usage',
                'indexes': [models.Index(fields=['user', 'period'], name='usage_user_id_1df339_idx'), models.Index(fields=['organization', 'period'], name='usage_organiz_737cd7_idx'), models.Index(fields=['-period'], name='usage_period_237f66_idx')],
                'unique_together': {('organization', 'period'), ('user', 'period')},
            },
        ),
    ]
