# Generated by Django 6.0 on 2026-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_subscription_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organização')], default='INDIVIDUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Grátis'), ('PRO', 'Profissional'), ('ENTERPRISE', 'Empresarial')], default='FREE', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('CANCELED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='ACTIVE', max_length=50),
        ),
    ]
