# Generated by Django 6.0 on 2025-12-22 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='LOGIN, CREATE_DOC, DELETE_DOC, QUERY_RAG, etc.', max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL se ação pessoal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['-created_at'], name='audit_logs_created_43fcd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list, help_text='Lista de fontes/trechos usados')),
                ('latency_ms', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL se query pessoal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Query',
                'verbose_name_plural': 'Logs de Queries',
                'db_table': 'query_logs',
                'indexes': [models.Index(fields=['user', '-created_at'], name='query_logs_user_id_0e7784_idx'), models.Index(fields=['organization', '-created_at'], name='query_logs_organiz_6311bc_idx'), models.Index(fields=['-created_at'], name='query_logs_created_1a680b_idx')],
            },
        ),
    ]
