# Generated by Django 6.0 on 2025-12-22 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('USER', 'USER'), ('ORGANIZATION', 'ORGANIZATION')], default='USER', help_text='Escopo do documento: usuário ou organização.', max_length=20)),
                ('title', models.CharField(help_text='Título do documento.', max_length=255)),
                ('file_key', models.FileField(help_text='Chave no MinIO onde o documento está armazenado.', upload_to='documents/')),
                ('file_url', models.URLField(blank=True, help_text='URL acessível publicamente para o documento armazenado.', max_length=2048)),
                ('mime_type', models.CharField(default='application/pdf', help_text='Tipo MIME do documento.', max_length=100)),
                ('status', models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('PROCESSING', 'PROCESSING'), ('INDEXED', 'INDEXED'), ('FAILED', 'FAILED')], default='UPLOADED', help_text='Status atual do documento no fluxo de processamento.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais relacionados ao documento.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organização associada ao documento, se aplicável.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='Usuário que carregou o documento.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(help_text='Índice do chunk dentro do documento.')),
                ('text', models.TextField(help_text='Texto extraído deste chunk do documento.')),
                ('embedding', models.TextField(blank=True, help_text='Será vector(1536) com pgvector')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais relacionados ao chunk.')),
                ('document', models.ForeignKey(help_text='Documento ao qual este chunk pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Chunk de Documento',
                'verbose_name_plural': 'Chunks de Documentos',
                'db_table': 'document_chunks',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='documents_user_id_10766e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status'], name='documents_organiz_f70f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_created_291bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_status_f31a08_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
