# Generated by Django 6.0 on 2026-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scope',
            field=models.CharField(choices=[('USER', 'Usuário'), ('ORGANIZATION', 'Organização')], default='USER', help_text='Escopo do documento: usuário ou organização.', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Carregado'), ('PROCESSING', 'Processando'), ('INDEXED', 'Indexado'), ('FAILED', 'Falhou')], default='UPLOADED', help_text='Status atual do documento no fluxo de processamento.', max_length=20),
        ),
    ]
