# Generated by Django 6.0 on 2025-12-28 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username pode conter apenas letras, números, pontos, hífens e underscores.', regex='^[a-zA-Z0-9._-]+$')]),
        ),
    ]
